[project]
name = "lilybot"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "asyncpg>=0.30.0",
    "discord-py[voice]>=2.6.3",
    "humanize>=4.13.0",
    "loguru>=0.7.3",
    "python-dateutil>=2.9.0.post0",
]
